<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>StudioDisplayXdr</AssemblyName>
    <RootNamespace>StudioDisplayXdr.App</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>..\..\assets\StudioDisplayXdr.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibUsbDotNet" Version="2.2.29" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\..\assets\StudioDisplayXdr.ico" Link="StudioDisplayXdr.ico" />
  </ItemGroup>

</Project>
