param(
    [string]$OutputPath = (Join-Path (Split-Path -Parent $PSScriptRoot) "profiles\StudioDisplayXDR-DisplayP3.icm")
)

$ErrorActionPreference = "Stop"

function New-ByteList {
    return ,([System.Collections.Generic.List[byte]]::new())
}

function Add-Bytes([System.Collections.Generic.List[byte]]$List, [byte[]]$Bytes) {
    $List.AddRange($Bytes)
}

function Get-AsciiBytes([string]$Text) {
    [Text.Encoding]::ASCII.GetBytes($Text)
}

function Get-U16BE([int]$Value) {
    $bytes = [BitConverter]::GetBytes([uint16]$Value)
    [Array]::Reverse($bytes)
    $bytes
}

function Get-U32BE([long]$Value) {
    $bytes = [BitConverter]::GetBytes([uint32]$Value)
    [Array]::Reverse($bytes)
    $bytes
}

function Get-S15Fixed16BE([double]$Value) {
    $fixed = [int32][Math]::Round($Value * 65536.0)
    $bytes = [BitConverter]::GetBytes($fixed)
    [Array]::Reverse($bytes)
    $bytes
}

function Add-Pad4([System.Collections.Generic.List[byte]]$List) {
    while (($List.Count % 4) -ne 0) {
        $List.Add(0)
    }
}

function New-TextTag([string]$Text) {
    $tag = New-ByteList
    Add-Bytes $tag (Get-AsciiBytes "text")
    Add-Bytes $tag ([byte[]](0,0,0,0))
    Add-Bytes $tag (Get-AsciiBytes ($Text + [char]0))
    Add-Pad4 $tag
    $tag.ToArray()
}

function New-DescTag([string]$Text) {
    $ascii = Get-AsciiBytes ($Text + [char]0)
    $tag = New-ByteList
    Add-Bytes $tag (Get-AsciiBytes "desc")
    Add-Bytes $tag ([byte[]](0,0,0,0))
    Add-Bytes $tag (Get-U32BE $ascii.Length)
    Add-Bytes $tag $ascii
    Add-Bytes $tag (Get-U32BE 0)
    Add-Bytes $tag (Get-U32BE 0)
    Add-Bytes $tag (Get-U16BE 0)
    $tag.Add(0)
    Add-Bytes $tag ([byte[]](0) * 67)
    Add-Pad4 $tag
    $tag.ToArray()
}

function New-XYZTag([double]$X, [double]$Y, [double]$Z) {
    $tag = New-ByteList
    Add-Bytes $tag (Get-AsciiBytes "XYZ ")
    Add-Bytes $tag ([byte[]](0,0,0,0))
    Add-Bytes $tag (Get-S15Fixed16BE $X)
    Add-Bytes $tag (Get-S15Fixed16BE $Y)
    Add-Bytes $tag (Get-S15Fixed16BE $Z)
    Add-Pad4 $tag
    $tag.ToArray()
}

function New-CurveTag([double]$Gamma) {
    $tag = New-ByteList
    Add-Bytes $tag (Get-AsciiBytes "curv")
    Add-Bytes $tag ([byte[]](0,0,0,0))
    Add-Bytes $tag (Get-U32BE 1)
    Add-Bytes $tag (Get-U16BE ([int][Math]::Round($Gamma * 256.0)))
    Add-Pad4 $tag
    $tag.ToArray()
}

function Set-Bytes([byte[]]$Target, [int]$Offset, [byte[]]$Bytes) {
    [Array]::Copy($Bytes, 0, $Target, $Offset, $Bytes.Length)
}

$description = "Studio Display XDR Display P3 D65 G2.2 (Generated)"
$copyright = "Generated by 2026 Apple Studio Display XDR Windows Override. Not an Apple-authored reference profile."

# D50-adapted Display P3 colorants with D65 source white.
$tags = [ordered]@{
    "desc" = New-DescTag $description
    "cprt" = New-TextTag $copyright
    "wtpt" = New-XYZTag 0.9642 1.0000 0.8249
    "rXYZ" = New-XYZTag 0.51512 0.24120 -0.00105
    "gXYZ" = New-XYZTag 0.29198 0.69225 0.04189
    "bXYZ" = New-XYZTag 0.15710 0.06657 0.78407
    "rTRC" = New-CurveTag 2.2
    "gTRC" = New-CurveTag 2.2
    "bTRC" = New-CurveTag 2.2
}

$tagTableLength = 4 + ($tags.Count * 12)
$dataOffset = 128 + $tagTableLength
$records = @()
$payload = New-ByteList

foreach ($entry in $tags.GetEnumerator()) {
    while ((($dataOffset + $payload.Count) % 4) -ne 0) {
        $payload.Add(0)
    }

    $offset = $dataOffset + $payload.Count
    $data = [byte[]]$entry.Value
    Add-Bytes $payload $data
    $records += [pscustomobject]@{
        Signature = $entry.Key
        Offset = $offset
        Size = $data.Length
    }
}

$profileSize = 128 + $tagTableLength + $payload.Count
$header = [byte[]]::new(128)
Set-Bytes $header 0 (Get-U32BE $profileSize)
Set-Bytes $header 4 (Get-AsciiBytes "STXW")
Set-Bytes $header 8 (Get-U32BE 0x02400000)
Set-Bytes $header 12 (Get-AsciiBytes "mntr")
Set-Bytes $header 16 (Get-AsciiBytes "RGB ")
Set-Bytes $header 20 (Get-AsciiBytes "XYZ ")

$now = Get-Date
$dateOffset = 24
foreach ($part in @($now.Year, $now.Month, $now.Day, $now.Hour, $now.Minute, $now.Second)) {
    Set-Bytes $header $dateOffset (Get-U16BE $part)
    $dateOffset += 2
}

Set-Bytes $header 36 (Get-AsciiBytes "acsp")
Set-Bytes $header 40 (Get-AsciiBytes "MSFT")
Set-Bytes $header 48 (Get-AsciiBytes "APPL")
Set-Bytes $header 52 (Get-AsciiBytes "AE42")
Set-Bytes $header 68 (Get-S15Fixed16BE 0.9642)
Set-Bytes $header 72 (Get-S15Fixed16BE 1.0000)
Set-Bytes $header 76 (Get-S15Fixed16BE 0.8249)
Set-Bytes $header 80 (Get-AsciiBytes "STXW")

$profile = New-ByteList
Add-Bytes $profile $header
Add-Bytes $profile (Get-U32BE $tags.Count)

foreach ($record in $records) {
    Add-Bytes $profile (Get-AsciiBytes $record.Signature)
    Add-Bytes $profile (Get-U32BE $record.Offset)
    Add-Bytes $profile (Get-U32BE $record.Size)
}

Add-Bytes $profile $payload.ToArray()

$destination = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $destination)) {
    New-Item -ItemType Directory -Force -Path $destination | Out-Null
}

[IO.File]::WriteAllBytes($OutputPath, $profile.ToArray())
Get-Item -LiteralPath $OutputPath
